# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-18 02:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_authors', '0002_author_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='books',
            field=models.ManyToManyField(to='book_authors.Book'),
        ),
    ]
