# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-19 19:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('initial_b', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='review',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
    ]
