# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-19 19:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('initial_b', '0003_auto_20180419_1243'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='rating',
        ),
    ]
